#!/usr/bin/env ruby
# -*- ruby -*-

require 'tk'

# http://svn.python.org/projects/external/tk-8.5.2.0/library/obsolete.tcl
# Tk.tk_call "::tk::classic::restore"

root = TkRoot.new {
  title "tkma"
}

root = panes = TkPanedWindow.new(root) {
  orient "vertical"
}

folders = TkFrame.new(root) {
  pack
}

$rescan_opts = "-thread"
$scan = TkVariable.new
def rescan(inc=false)
  `coma inc #{$folder}`  if inc
  $scan.value = `coma read #{$folder} -width #{textwidth} #{$rescan_opts}`.split("\n")
end

def textwidth
  # XXX good enough for now
  ($mailcontent.winfo_width - $mailcontent.borderwidth) /
    TkFont.measure("TkFixedFont", "0") - 1
end

# XXX wrap?
%w{+audvidsyn +lispmachines}.each { |folder|
  TkButton.new(folders) {
    text folder
    padx 3
    pady 1
    command {
      $folder = folder
      rescan true
    }
    pack "side" => "left"
  }
}

toc = TkFrame.new(root) {
  pack :expand => true, :fill => "x"
}

tocbuttons = TkFrame.new(toc) {
  pack :expand => false, :fill => "both", :anchor => "ne"
}
%w{all date from subject thread flagged unflagged replied unreplied seen unseen}.each { |btn|
  TkButton.new(tocbuttons) {
    text btn
    padx 3
    pady 1
    command {
      $rescan_opts = "-" + btn
      rescan
    }
    pack "side" => "right"
  }
}

$redisplay_opts = []
def redisplay
  sel = $mails.get($mails.curselection)[/\d+/]
  $mailcontent.state = 'normal'
  $mailcontent.value = `coma show #{sel} #{$redisplay_opts.join(" ")}`
  $mailcontent.state = 'disabled'
end

$mails = TkScrollbox.new(toc) {
  insert 0, "foo"
  insert 0, "bar"
  font "TkFixedFont"
  listvariable $scan
  pack :expand => true, :fill => "both"

  bind("<ListboxSelect>") {
    redisplay
  }
}

mail = TkFrame.new(root) {
  pack :expand => true, :fill => "both"
}

mailbuttons = TkFrame.new(mail) {
  pack :expand => false, :fill => "both", :anchor => "ne"
}

TkButton.new(mailbuttons) {
    padx 3
    pady 1
  text "repl"
  command { xxx }
  pack "side" => "right"
}
TkButton.new(mailbuttons) {
    padx 3
    pady 1
  text "fwd"
  command { xxx }
  pack "side" => "right"
}
TkButton.new(mailbuttons) {
    padx 3
    pady 1
  text "raw"
  command {
    unless $redisplay_opts.delete "-raw"
      $redisplay_opts << "-raw"
    end
    redisplay
  }
  pack "side" => "right"
}

$mailcontent = TkText.new(mail) {
  yscrollbar(TkScrollbar.new(mail).pack(:fill=>:y, :side=>:right))
  state 'disabled'
  insert "0.0", "foobar"

  pack :expand => true, :fill => "both", :anchor => "s"
}

panes.add folders
panes.add toc
panes.add mail
panes.pack(:expand => true, :fill => "both")

Tk.mainloop
